// src/lib/Plugins.svelte
<script lang="ts">
  type Plugin = {
    name: string;
    url: string;
    likes: number;
    likesShort: string;
    runs: number;
    runsShort: string;
  };

  let plugins = $state<Plugin[]>([]);

  const toShortNum = (n: number): string => {
    if (n < 1e3) return n.toString();
    if (n >= 1e3) return (n / 1e3).toFixed(1) + "k";
    return n.toString();
  };

  $effect(() => {
    (async () => {
      try {
        // Fetch from static JSON file updated by GitHub Actions
        const response = await fetch("/plugins.json");
        const data = await response.json();

        const newPluginData: Plugin[] = data.meta.map((plugin: any) => {
          return {
            url: `https://www.figma.com/community/plugin/${plugin.id}`,
            name: (Object.values(plugin.versions)[0] as any).name,
            likes: plugin.like_count,
            likesShort: toShortNum(plugin.like_count),
            runs: plugin.unique_run_count,
            runsShort: toShortNum(plugin.unique_run_count)
          };
        });

        // Sort by runs
        const sortedPlugins = newPluginData.sort((a, b) => b.runs - a.runs);

        // Exclude cloned plugins
        const clonedPlugins = ["1050439261870735490", "1052604096433126717"];
        plugins = sortedPlugins.filter(
          (plugin) => !clonedPlugins.includes(plugin.url.split("/").pop() || "")
        );
      } catch (error) {
        console.error("Error fetching plugins:", error);
      }
    })();
  });
</script>

<section class="section">
  <h2 class="section-title">Figma plugins</h2>

  <div class="section-grid">
    {#each plugins as plugin}
      <a
        href={plugin.url}
        target="_blank"
        rel="noopener noreferrer"
        class="link-card"
      >
        <h3 class="card-title">{plugin.name}</h3>
        <div class="card-meta">
          <span>{plugin.runsShort} installs</span>
          <span>∙</span>
          <span>{plugin.likesShort} likes</span>
        </div>
      </a>
    {/each}
  </div>
</section>

// sections/Plugins/index.tsx
import React from "react";

import { Section, CardContent, Skeleton } from "../../components";
import { toShortNum } from "../../utils";

const Plugins: React.FC = () => {
  const [pluginsData, setPluginsData] = React.useState<any>([]);

  // FETCH DATA
  React.useEffect(() => {
    // fetch data from api
    const fetchUrl =
      "https://www.figma.com/api/plugins/profile/134689?fuid=987658461863261647";

    // cors proxy
    const proxyUrl = "https://corsproxy.io/?";

    fetch(proxyUrl + fetchUrl)
      .then((response) => response.json())
      .then((data) => {
        const newPluginData = data.meta.map((plugin: any) => {
          return {
            url: `https://www.figma.com/community/plugin/${plugin.id}`,
            name: (Object.values(plugin.versions)[0] as any).name,
            img: (Object.values(plugin.versions)[0] as any).redirect_icon_url,
            likes: plugin.like_count,
            likesShort: toShortNum(plugin.like_count),
            runs: plugin.unique_run_count,
            runsShort: toShortNum(plugin.unique_run_count)
          };
        });

        const resortedPluginData = newPluginData.sort(
          (a: any, b: any) => b.runs - a.runs
        );

        // exclude cloned plugin
        const clonedPlugins = ["1050439261870735490", "1052604096433126717"];

        // remove plugin with id 1050439261870735490
        const removeClonedPlugin = resortedPluginData.filter(
          (plugin: any) => !clonedPlugins.includes(plugin.url.split("/").pop())
        );

        setPluginsData(removeClonedPlugin);
      });
  }, []);

  return (
    <Section
      title="Plugins"
      description={
        <>
          I have created many Figma plugins for different purposes. If I see
          that the work process can be optimized, I try to do so. It helps free
          up time for other tasks and make the process more efficient. All my
          plugins I have made are open source and completely free.
        </>
      }
    >
      {pluginsData.length !== 0
        ? // RENDER PLUGINS
          pluginsData.map((plugin: any, index: number) => {
            return (
              <CardContent
                key={`${plugin.name}-${index}`}
                title={plugin.name}
                icon={plugin.img}
                stat={[
                  { name: "Likes", value: plugin.likesShort },
                  { name: "Runs", value: plugin.runsShort }
                ]}
                link={plugin.url}
              />
            );
          })
        : Array(13)
            .fill(0)
            .map((_, i) => <Skeleton key={i} />)}
    </Section>
  );
};

export default Plugins;
